rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  
  root 'job_offers#index'

  authenticate :admin do
    namespace :admin do
      root :to => "job_offers#index"
      resources :job_offers
      resources :job_titles
      resources :companies
      resources :countries
      resources :cities
      resources :technologies
      resources :salary_periods
      resources :currencies
      resources :employment_types
      resources :work_types
    end
  end

  resources :job_offers, only: [:index, :show] do
    collection do
      get :search, :action => 'search_redirect', :as => 'search'
      get 'sae/:search_what/:search_where', :action => 'search', :constraints => { :search_what => /[^\/]+/ }, :as => 'search_what_where'
      get 'sa/:search_what', :action => 'search', :constraints => { :search_what => /[^\/]+/ }, :as => 'search_what'
      get 'se/:search_where', :action => 'search', :constraints => { :search_what => /[^\/]+/ }, :as => 'search_where'
    end
  end 
end

rails/app/models/job_offer.rb
class JobOffer < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_what,
    against: [:title, :description],
    associated_against: {
      job_title: :name,
      technologies: :name,
      company: :name
    },
    :using => {
      :tsearch => {:any_word => true, :dictionary => "english"}
    }

  pg_search_scope :search_where,
    associated_against: {
      country: [:name, :code],
      city: :name
    },
    :using => {
      :tsearch => {:any_word => true, :dictionary => "english"}
    }

  default_scope { order(:created_at => :desc) }
  self.per_page = 25

  belongs_to :company
  belongs_to :job_title
  belongs_to :country
  belongs_to :city
  has_and_belongs_to_many :technologies
  belongs_to :currency
  belongs_to :salary_period
  belongs_to :employment_type
  belongs_to :work_type

  def to_param
    [id, title.parameterize].join("-")
  end

  attr_reader :job_title_token
  attr_reader :company_token
  attr_reader :country_token
  attr_reader :city_token
  attr_reader :technology_tokens

  def job_title_token=(token)
    self.job_title_id = JobTitle.id_from_token(token)
  end

  def company_token=(token)
    self.company_id = Company.id_from_token(token)
  end

  def country_token=(token)
    self.country_id = Country.id_from_token(token)
  end

  def city_token=(token)
    self.city_id = City.id_from_token(token)
  end

  def technology_tokens=(tokens)
    self.technology_ids = Technology.ids_from_tokens(tokens)
  end

end

rails/app/controllers/admin/job_offers_controller.rb
class Admin::JobOffersController < ApplicationController
  before_action :set_job_offer, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  def index
    @job_offers = JobOffer.all
  end

  def show
  end

  def new
    @job_offer = JobOffer.new
    @job_offer.active_to = 45.days.from_now
  end

  def edit
  end

  def create
    @job_offer = JobOffer.new(job_offer_params)

    respond_to do |format|
      if @job_offer.save
        format.html { redirect_to admin_job_offer_path(@job_offer.id), notice: 'Job offer was successfully created.' }
        format.json { render :show, status: :created, location: @job_offer }
      else
        format.html { render :new }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @job_offer.update(job_offer_params)
        format.html { redirect_to admin_job_offer_path(@job_offer), notice: 'Job offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_offer }
      else
        format.html { render :edit }
        format.json { render json: @job_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job_offer.destroy
    respond_to do |format|
      format.html { redirect_to admin_job_offers_path, notice: 'Job offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_offer
      @job_offer = JobOffer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_offer_params
      params.require(:job_offer).permit(
        :title,
        :job_title_token,
        :link,
        :company_token,
        :description,
        :country_token,
        :city_token,
        :address,
        :company_name,
        :technology_tokens,
        :is_active,
        :active_to,
        :salary_from,
        :salary_to,
        :currency_id,
        :salary_period_id,
        :employment_type_id,
        :work_type_id
      )
    end
end

rails/app/controllers/job_offers_controller.rb
class JobOffersController < ApplicationController
  before_action :set_job_offer, only: [:show]

  def index
    @job_offers = JobOffer
      .where(is_active: true)
      .where("active_to >= :now", now: DateTime.now)
      .page(params[:page])
  end

  def show
  end

  # SEARCHNIG ==========
  def search_redirect
    # this function is called when you are using search form - it redirects to more nice and seo friendly path
    if params[:search_what].present? && params[:search_where].present?
      redirect_to search_what_where_job_offers_path(params[:search_what], params[:search_where])
    elsif params[:search_what].present?
      redirect_to search_what_job_offers_path(params[:search_what])
    elsif params[:search_where].present?
      redirect_to search_where_job_offers_path(params[:search_where])
    else
      redirect_to job_offers_path
    end
  end

  def search
    # search is based on two fields so that's why there is so much stuff here
    if params[:search_what].present? && params[:search_where].present?
      @what = params[:search_what].gsub(/-/, ' ').titleize
      @where = params[:search_where].gsub(/-/, ' ').titleize
      @search_query = @what + ' jobs in ' + @where

      @job_offers = JobOffer
        .where(is_active: true)
        .where("active_to >= :now", now: DateTime.now)
        .search_what(@what)
        .search_where(@where)
        .page(params[:page])

    elsif params[:search_what].present?
      @what = params[:search_what].gsub(/-/, ' ').titleize
      @search_query = @what + ' jobs'

      @job_offers = JobOffer
        .where(is_active: true)
        .where("active_to >= :now", now: DateTime.now)
        .search_what(@what)
        .page(params[:page])

    elsif params[:search_where].present?
      @where = params[:search_where].gsub(/-/, ' ').titleize
      @search_query = 'IT jobs in ' + @where
      
      @job_offers = JobOffer
        .where(is_active: true)
        .where("active_to >= :now", now: DateTime.now)
        .search_where(@where)
        .page(params[:page])

    else
      redirect_to job_offers_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_offer
      @job_offer = JobOffer.find(params[:id])

      unless @job_offer.active_to >= DateTime.now && @job_offer.is_active
        flash[:error] ||= []
        flash[:error] << 'Oops! This job offer is no longer active. Check out our latest ones.'
        redirect_to job_offers_path
      end
    end
end

rails/app/helpers/job_offers_helper.rb
module JobOffersHelper
end

rails/app/views/admin/job_offers/_form.html.erb
<div class="row">
  <%= form_for [:admin, @job_offer], html: {class: 'col s12'} do |f| %>
    
    <%# TITLE %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :title %>
        <%= f.label :title %>
      </div>
    </div>

    <div class="row">
      
      <%# JOB TITLE %>
      <div class="col s6">
        <%= f.label :job_title_token, "Job Title" %><br>
        <%= f.text_field :job_title_token, class: 'job-offers-page__job-title-field', data: {load: '['+ ( @job_offer.job_title ? @job_offer.job_title.to_json : '') +']'} %>
      </div>

      <%# COMPANY %>
      <div class="col s6">
        <%= f.label :company_token, "Company" %><br>
        <%= f.text_field :company_token, class: 'job-offers-page__company-field', data: {load: '['+ ( @job_offer.company ? @job_offer.company.to_json : '') +']'} %>
      </div>
    </div>

    <%# LINK %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :link %>
        <%= f.label :link %>
      </div>
    </div>

    <%# DESCRIPTION %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_area :description, class: 'materialize-textarea' %>
        <%= f.label :description %>
      </div>
    </div>

    <div class="row">
      
      <%# COUNTRY %>
      <div class="col s6">
        <%= f.label :country_token, "Country" %><br>
        <%= f.text_field :country_token, class: 'job-offers-page__country-field', data: {load: '['+ ( @job_offer.country ? @job_offer.country.to_json : '') +']'} %>
      </div>

      <%# CITY %>
      <div class="col s6">
        <%= f.label :city_token, "City" %><br>
        <%= f.text_field :city_token, class: 'job-offers-page__city-field', data: {load: '['+ (@job_offer.city ? @job_offer.city.to_json : '') +']'} %>
      </div>
    </div>


    <div class="row">
      
      <%# ADDRESS %>
      <div class="input-field col s6">
        <%= f.text_area :address, class: 'materialize-textarea' %>
        <%= f.label :address %>
      </div>

      <%# TECHNOLOGIES %>
      <div class="col s6">
        <%= f.label :technology_tokens, "Technologies" %><br>
        <%= f.text_field :technology_tokens, class: 'job-offers-page__technologies-field', data: {load: @job_offer.technologies} %>
      </div>
    </div>

    <div class="row">
      
      <%# IS ACTIVE? %>
      <div class="col s6">
        <%= f.label :is_active, "Is offer active?" %><br>
        <div class="switch">
          <label>
            Off
            <%= f.check_box :is_active %>
            <span class="lever"></span>
            On
          </label>
        </div>
      </div>
      
      <%# ACTIVE TO %>
      <div class="col s6">
        <%= f.label :active_to, "Offer active to (45 days in advance by default)" %>
        <%= f.date_field :active_to, class: 'datepicker' %>
      </div>
    </div>

    <div class="row">
      
      <%# SALARY FROM %>
      <div class="input-field col s3">
        <%= f.label :salary_from, "Salary from" %>
        <%= f.text_field :salary_from %>
      </div>

      <%# SALARY TO %>
      <div class="input-field col s3">
        <%= f.label :salary_to, "Salary to" %>
        <%= f.text_field :salary_to %>
      </div>
      
      <%# CURRENCY %>
      <div class="input-field col s3">
        <%=
          f.select :currency_id,
            options_for_select(
              Currency.all.map{ |c| [c.sign, c.id] },
              selected_key = f.object.currency_id
            ),
            {:include_blank => 'Currency...'}
        %>
        <%= f.label :currency_id, "Currency" %>
      </div>

      <%# SALARY PERIOD %>
      <div class="input-field col s3">
        <%=
          f.select :salary_period_id,
            options_for_select(
              SalaryPeriod.all.map{ |c| [c.period, c.id] },
              selected_key = f.object.salary_period_id
            ),
            {:include_blank => 'Salary period...'}
        %>
        <%= f.label :salary_period_id, "Salary period" %>
      </div>
    </div>

    <div class="row">

      <%# EMPLYMENT TYPE %>
      <div class="input-field col s6">
        <%=
          f.select :employment_type_id,
            options_for_select(
              EmploymentType.all.map{ |c| [c.name, c.id] },
              selected_key = f.object.employment_type_id
            ),
            {:include_blank => 'Employment type...'}
        %>
        <%= f.label :employment_type_id, "Employment type" %>
      </div>

      <%# WORK TYPE %>
      <div class="input-field col s6">
        <%=
          f.select :work_type_id,
            options_for_select(
              WorkType.all.map{ |c| [c.name, c.id] },
              selected_key = f.object.work_type_id
            ),
            {:include_blank => 'Work type...'}
        %>
        <%= f.label :employment_type_id, "Work type" %>
      </div>
    </div>

    <%# SUBMIT BUTTON %>
    <div class="row">
      <div class="col s12"> 
        <%= button_tag(type: "submit", class: "btn waves-effect waves-light") do %>
          Submit <i class="material-icons right">send</i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

rails/app/views/admin/job_offers/edit.html.erb
<div class="job-offers-page job-offers-page_edit">
  <div class="row">
    <div class="col s12">
      <h1>Editing Job Offer</h1>

      <%= render 'form' %>

      <%= link_to 'Show', admin_job_offer_path(@job_offer) %> |
      <%= link_to 'Back', admin_job_offers_path %>
    </div>
  </div>
</div>

rails/app/views/admin/job_offers/index.html.erb
<div class="job-offers-page job-offers-page_index">
  <div class="row">
    <div class="col s12">
      <h1>Listing Job Offers</h1>

      <%= link_to 'New Job offer', new_admin_job_offer_path %>

      <br />

      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Company</th>
            <th>Country</th>
            <th>City</th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
          <% @job_offers.each do |job_offer| %>
            <tr>
              <td><%= link_to job_offer.title, admin_job_offer_path(job_offer) %></td>
              <td><%= job_offer.company.name if job_offer.company %></td>
              <td><%= job_offer.country.name if job_offer.country %></td>
              <td><%= job_offer.city.name if job_offer.city %></td>
              <td><%= link_to 'Edit', edit_admin_job_offer_path(job_offer) %></td>
              <td><%= link_to 'Destroy', admin_job_offer_path(job_offer), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Job offer', new_admin_job_offer_path %>
    </div>
  </div>
</div>

rails/app/views/admin/job_offers/new.html.erb
<div class="job-offers-page job-offers-page_new">
  <div class="row">
    <div class="col s12">
      <h1 class="header">New Job Offer</h1>

      <%= render 'form' %>

      <%= link_to 'Back', admin_job_offers_path %>
    </div>
  </div>
</div>

rails/app/views/admin/job_offers/show.html.erb
<div class="job-offers-page job-offers-page_show">
  <div class="row">
    <div class="col s12">
      <%= link_to 'Edit', edit_admin_job_offer_path(@job_offer) %> |
      <%= link_to 'Back', admin_job_offers_path %>

      <p>
        <strong>Title:</strong>
        <%= @job_offer.title %>
      </p>

      <p>
        <strong>Job title:</strong>
        <%= @job_offer.job_title.name if @job_offer.job_title %>
      </p>

      <p>
        <strong>Company:</strong>
        <%= @job_offer.company.name if @job_offer.company %>
      </p>

      <p>
        <strong>Link:</strong>
        <%= link_to @job_offer.link, @job_offer.link, target: '_blank' %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= simple_format(@job_offer.description) %>
      </p>

      <p>
        <strong>Country:</strong>
        <%= @job_offer.country.name if @job_offer.country %>
      </p>

      <p>
        <strong>City:</strong>
        <%= @job_offer.city.name if @job_offer.city %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @job_offer.address %>
      </p>

      <p>
        <strong>Technologies:</strong>
        <ul>
          <% @job_offer.technologies.each do |technology| %>
            <li><%= technology.name %></li>
          <% end %>
        </ul>
      </p>

      <p>
        <strong>Is offer active:</strong>
        <%= @job_offer.is_active %>
      </p>

      <p>
        <strong>Offer is active to:</strong>
        <%= @job_offer.active_to %>
      </p>

      <p>
        <strong>Sallary:</strong>
        <%= @job_offer.salary_from %> - <%= @job_offer.salary_to %> <%= @job_offer.currency.sign if @job_offer.currency %> <%= @job_offer.salary_period.period if @job_offer.salary_period %>
      </p>

      <p>
        <strong>Employment type:</strong>
        <%= @job_offer.employment_type.name if @job_offer.employment_type %>
      </p>

      <p>
        <strong>Work type:</strong>
        <%= @job_offer.work_type.name if @job_offer.work_type %>
      </p>

      <%= link_to 'Edit', edit_admin_job_offer_path(@job_offer) %> |
      <%= link_to 'Back', admin_job_offers_path %>
    </div>
  </div>
</div> 