rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  
  root 'job_offers#index'

  authenticate :admin do
    namespace :admin do
      root :to => "job_offers#index"
      resources :job_offers
      resources :job_titles
      resources :companies
      resources :countries
      resources :cities
      resources :technologies
      resources :salary_periods
      resources :currencies
      resources :employment_types
      resources :work_types
    end
  end

  resources :job_offers, only: [:index, :show] do
    collection do
      get :search, :action => 'search_redirect', :as => 'search'
      get 'sae/:search_what/:search_where', :action => 'search', :constraints => { :search_what => /[^\/]+/ }, :as => 'search_what_where'
      get 'sa/:search_what', :action => 'search', :constraints => { :search_what => /[^\/]+/ }, :as => 'search_what'
      get 'se/:search_where', :action => 'search', :constraints => { :search_what => /[^\/]+/ }, :as => 'search_where'
    end
  end 
end

rails/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable, :recoverable, :validatable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable
end

rails/app/models/city.rb
class City < ActiveRecord::Base
  has_many :job_offers
  belongs_to :country

  def self.tokens(query)
    cities = where("lower(name) like ?", "%#{query.downcase}%")
    if cities.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      cities.unshift({id: "<<<#{query}>>>", name: "New: \"#{query}\""})
    end
  end

  def self.id_from_token(token)
    token.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    token
  end
end

rails/app/models/company.rb
class Company < ActiveRecord::Base
  has_many :job_offers

  def self.tokens(query)
    companies = where("lower(name) like ?", "%#{query.downcase}%")
    if companies.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      companies.unshift({id: "<<<#{query}>>>", name: "New: \"#{query}\""})
    end
  end

  def self.id_from_token(token)
    token.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    token
  end
end

rails/app/models/country.rb
class Country < ActiveRecord::Base
  has_many :job_offers
  has_many :cities

  def self.tokens(query)
    countries = where("lower(name) like ?", "%#{query.downcase}%")
    if countries.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      countries.unshift({id: "<<<#{query}>>>", name: "New: \"#{query}\""})
    end
  end

  def self.id_from_token(token)
    token.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    token
  end
end

rails/app/models/currency.rb
class Currency < ActiveRecord::Base
  has_many :job_offers
end

rails/app/models/employment_type.rb
class EmploymentType < ActiveRecord::Base
  has_many :job_offers
end

rails/app/models/job_offer.rb
class JobOffer < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_what,
    against: [:title, :description],
    associated_against: {
      job_title: :name,
      technologies: :name,
      company: :name
    },
    :using => {
      :tsearch => {:any_word => true, :dictionary => "english"}
    }

  pg_search_scope :search_where,
    associated_against: {
      country: [:name, :code],
      city: :name
    },
    :using => {
      :tsearch => {:any_word => true, :dictionary => "english"}
    }

  default_scope { order(:created_at => :desc) }
  self.per_page = 25

  belongs_to :company
  belongs_to :job_title
  belongs_to :country
  belongs_to :city
  has_and_belongs_to_many :technologies
  belongs_to :currency
  belongs_to :salary_period
  belongs_to :employment_type
  belongs_to :work_type

  def to_param
    [id, title.parameterize].join("-")
  end

  attr_reader :job_title_token
  attr_reader :company_token
  attr_reader :country_token
  attr_reader :city_token
  attr_reader :technology_tokens

  def job_title_token=(token)
    self.job_title_id = JobTitle.id_from_token(token)
  end

  def company_token=(token)
    self.company_id = Company.id_from_token(token)
  end

  def country_token=(token)
    self.country_id = Country.id_from_token(token)
  end

  def city_token=(token)
    self.city_id = City.id_from_token(token)
  end

  def technology_tokens=(tokens)
    self.technology_ids = Technology.ids_from_tokens(tokens)
  end

end

rails/app/models/job_title.rb
class JobTitle < ActiveRecord::Base
  has_many :job_offers

  def self.tokens(query)
    job_titles = where("lower(name) like ?", "%#{query.downcase}%")
    if job_titles.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      job_titles.unshift({id: "<<<#{query}>>>", name: "New: \"#{query}\""})
    end
  end

  def self.id_from_token(token)
    token.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    token
  end
end

rails/app/models/salary_period.rb
class SalaryPeriod < ActiveRecord::Base
  has_many :job_offers
end

rails/app/models/technology.rb
class Technology < ActiveRecord::Base
  has_and_belongs_to_many :job_offers

  def self.tokens(query)
    technologies = where("lower(name) like ?", "%#{query.downcase}%")
    if technologies.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      technologies.unshift({id: "<<<#{query}>>>", name: "New: \"#{query}\""})
    end
  end

  def self.ids_from_tokens(tokens)
    tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    tokens.split(',')
  end
end

rails/app/models/work_type.rb
class WorkType < ActiveRecord::Base
  has_many :job_offers
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/cities_helper.rb
module CitiesHelper
end

rails/app/helpers/companies_helper.rb
module CompaniesHelper
end

rails/app/helpers/countries_helper.rb
module CountriesHelper
end

rails/app/helpers/currencies_helper.rb
module CurrenciesHelper
end

rails/app/helpers/job_offers_helper.rb
module JobOffersHelper
end

rails/app/helpers/job_titles_helper.rb
module JobTitlesHelper
end

rails/app/helpers/technologies_helper.rb
module TechnologiesHelper
end

rails/app/helpers/work_types_helper.rb
module WorkTypesHelper
end

rails/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rebase.IT - Administration panel</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <ul id="others-dropdown" class="dropdown-content">
    <li><%= link_to('Job Titles', admin_job_titles_path) %></li>
    <li><%= link_to('Companies', admin_companies_path) %></li>
    <li><%= link_to('Countries', admin_countries_path) %></li>
    <li><%= link_to('Cities', admin_cities_path) %></li>
    <li><%= link_to('Technologies', admin_technologies_path) %></li>
    <li><%= link_to('Employment Types', admin_employment_types_path) %></li>
    <li><%= link_to('Work Types', admin_work_types_path) %></li>
    <li><%= link_to('Salary Periodes', admin_salary_periods_path) %></li>
    <li><%= link_to('Currencies', admin_currencies_path) %></li>
  </ul>
  <nav class="main-nav">
    <div class="nav-wrapper main-nav__wrapper">
      <%= link_to admin_job_offers_path, class: 'brand-logo main-nav__logo' do %>
        <span
          itemprop="name">
          REBASE.IT
        </span>
      <% end %>
      <a href="#" data-activates="mobile-navbar" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to('View Website', root_path) %></li>
        <li><%= link_to('Job Offers', admin_job_offers_path) %></li>
        <li>
          <a 
            class="dropdown-button"
            href="#!"
            data-activates="others-dropdown">
            Others<i class="material-icons right">arrow_drop_down</i>
          </a>
        </li>
        <% if admin_signed_in? %>
          <li>
            <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>        
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_admin_session_path)  %>  
          </li>
        <% end %>
      </ul>

      <ul class="side-nav" id="mobile-navbar">
        <li><%= link_to('View Website', root_path) %></li>
        <li><%= link_to('Job Offers', admin_job_offers_path) %></li>
        <li><%= link_to('Job Titles', admin_job_titles_path) %></li>
        <li><%= link_to('Companies', admin_companies_path) %></li>
        <li><%= link_to('Countries', admin_countries_path) %></li>
        <li><%= link_to('Cities', admin_cities_path) %></li>
        <li><%= link_to('Technologies', admin_technologies_path) %></li>
        <li><%= link_to('Employment Types', admin_employment_types_path) %></li>
        <li><%= link_to('Work Types', admin_work_types_path) %></li>
        <li><%= link_to('Salary Periodes', admin_salary_periods_path) %></li>
        <li><%= link_to('Currencies', admin_currencies_path) %></li>
        <% if admin_signed_in? %>
          <li>
            <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>        
          </li>
        <% else %>
          <li>
          <%= link_to('Login', new_admin_session_path)  %>  
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <div class="progress loading-indicator">
      <div class="indeterminate"></div>
  </div>
  <p class="notice"><%= notice %></p>
  <div class="container admin-section">
    <%= yield %>
  </div>
</body>
</html>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= (yield(:title) + " - " unless yield(:title).blank?).to_s + "Rebase.IT" %></title>
  <meta content="Latest job offers from London. Front-End and Back-End Web Developer jobs in the hottest technologies of 2016. Just Do It! Make Your Dreams Come True!" name="description">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body
  itemscope
  itemtype="http://schema.org/WebPage">

  <%# GOOGLE ANALYTICS %>
  <%= render :partial=>"shared/analytics" if Rails.env.production? %>

  <%# MAIN NAVIGATION %>
  <nav class="main-nav">
    <div class="nav-wrapper main-nav__wrapper">
      <%= link_to root_path, class: 'brand-logo main-nav__logo' do %>
        <span
          itemprop="name">
          Rebase.IT
        </span>
      <% end %>
    </div>
  </nav>

  <%# PROGRESS BAR %>
  <div class="progress loading-indicator">
      <div class="indeterminate"></div>
  </div>
  
  <div class="container">
    <div class="row">
      <div class="col s12 m3">
        <%= yield(:side) %>
        <%# SIDE NAV %>
        <%= render partial: 'shared/side_nav' %>
      </div>
      <div class="col s12 m9">
        
        <%# MAIN CONTENT %>
        <div
          class="main-content"
          itmeprop="mainContentOfPage">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>

  <%# FLASH MESSAGES - JS %>
  <script>
    <%= render partial: 'shared/flash.js' %>
  </script>
</body>
</html>