rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  
  root 'job_offers#index'

  authenticate :admin do
    namespace :admin do
      root :to => "job_offers#index"
      resources :job_offers
      resources :job_titles
      resources :companies
      resources :countries
      resources :cities
      resources :technologies
      resources :salary_periods
      resources :currencies
      resources :employment_types
      resources :work_types
    end
  end

  resources :job_offers, only: [:index, :show] do
    collection do
      get :search, :action => 'search_redirect', :as => 'search'
      get 'sae/:search_what/:search_where', :action => 'search', :constraints => { :search_what => /[^\/]+/ }, :as => 'search_what_where'
      get 'sa/:search_what', :action => 'search', :constraints => { :search_what => /[^\/]+/ }, :as => 'search_what'
      get 'se/:search_where', :action => 'search', :constraints => { :search_what => /[^\/]+/ }, :as => 'search_where'
    end
  end 
end

rails/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable, :recoverable, :validatable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable
end

rails/app/models/city.rb
class City < ActiveRecord::Base
  has_many :job_offers
  belongs_to :country

  def self.tokens(query)
    cities = where("lower(name) like ?", "%#{query.downcase}%")
    if cities.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      cities.unshift({id: "<<<#{query}>>>", name: "New: \"#{query}\""})
    end
  end

  def self.id_from_token(token)
    token.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    token
  end
end

rails/app/models/company.rb
class Company < ActiveRecord::Base
  has_many :job_offers

  def self.tokens(query)
    companies = where("lower(name) like ?", "%#{query.downcase}%")
    if companies.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      companies.unshift({id: "<<<#{query}>>>", name: "New: \"#{query}\""})
    end
  end

  def self.id_from_token(token)
    token.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    token
  end
end

rails/app/models/country.rb
class Country < ActiveRecord::Base
  has_many :job_offers
  has_many :cities

  def self.tokens(query)
    countries = where("lower(name) like ?", "%#{query.downcase}%")
    if countries.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      countries.unshift({id: "<<<#{query}>>>", name: "New: \"#{query}\""})
    end
  end

  def self.id_from_token(token)
    token.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    token
  end
end

rails/app/models/currency.rb
class Currency < ActiveRecord::Base
  has_many :job_offers
end

rails/app/models/employment_type.rb
class EmploymentType < ActiveRecord::Base
  has_many :job_offers
end

rails/app/models/job_offer.rb
class JobOffer < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_what,
    against: [:title, :description],
    associated_against: {
      job_title: :name,
      technologies: :name,
      company: :name
    },
    :using => {
      :tsearch => {:any_word => true, :dictionary => "english"}
    }

  pg_search_scope :search_where,
    associated_against: {
      country: [:name, :code],
      city: :name
    },
    :using => {
      :tsearch => {:any_word => true, :dictionary => "english"}
    }

  default_scope { order(:created_at => :desc) }
  self.per_page = 25

  belongs_to :company
  belongs_to :job_title
  belongs_to :country
  belongs_to :city
  has_and_belongs_to_many :technologies
  belongs_to :currency
  belongs_to :salary_period
  belongs_to :employment_type
  belongs_to :work_type

  def to_param
    [id, title.parameterize].join("-")
  end

  attr_reader :job_title_token
  attr_reader :company_token
  attr_reader :country_token
  attr_reader :city_token
  attr_reader :technology_tokens

  def job_title_token=(token)
    self.job_title_id = JobTitle.id_from_token(token)
  end

  def company_token=(token)
    self.company_id = Company.id_from_token(token)
  end

  def country_token=(token)
    self.country_id = Country.id_from_token(token)
  end

  def city_token=(token)
    self.city_id = City.id_from_token(token)
  end

  def technology_tokens=(tokens)
    self.technology_ids = Technology.ids_from_tokens(tokens)
  end

end

rails/app/models/job_title.rb
class JobTitle < ActiveRecord::Base
  has_many :job_offers

  def self.tokens(query)
    job_titles = where("lower(name) like ?", "%#{query.downcase}%")
    if job_titles.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      job_titles.unshift({id: "<<<#{query}>>>", name: "New: \"#{query}\""})
    end
  end

  def self.id_from_token(token)
    token.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    token
  end
end

rails/app/models/salary_period.rb
class SalaryPeriod < ActiveRecord::Base
  has_many :job_offers
end

rails/app/models/technology.rb
class Technology < ActiveRecord::Base
  has_and_belongs_to_many :job_offers

  def self.tokens(query)
    technologies = where("lower(name) like ?", "%#{query.downcase}%")
    if technologies.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      technologies.unshift({id: "<<<#{query}>>>", name: "New: \"#{query}\""})
    end
  end

  def self.ids_from_tokens(tokens)
    tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    tokens.split(',')
  end
end

rails/app/models/work_type.rb
class WorkType < ActiveRecord::Base
  has_many :job_offers
end

rails/app/controllers/admin/cities_controller.rb
class Admin::CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  def index
    @cities = City.order(:name)
    respond_to do |format|
      format.html
      format.json { render json: @cities.tokens(params[:q]) }
    end
  end

  def show
  end

  def new
    @city = City.new
  end

  def edit
  end

  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to admin_city_path(@city), notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to admin_city_path(@city), notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to admin_cities_path, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :country_id)
    end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/cities_helper.rb
module CitiesHelper
end

rails/app/helpers/companies_helper.rb
module CompaniesHelper
end

rails/app/helpers/countries_helper.rb
module CountriesHelper
end

rails/app/helpers/currencies_helper.rb
module CurrenciesHelper
end

rails/app/helpers/employment_types_helper.rb
module EmploymentTypesHelper
end

rails/app/helpers/job_offers_helper.rb
module JobOffersHelper
end

rails/app/helpers/job_titles_helper.rb
module JobTitlesHelper
end

rails/app/helpers/salary_periods_helper.rb
module SalaryPeriodsHelper
end

rails/app/helpers/technologies_helper.rb
module TechnologiesHelper
end

rails/app/helpers/work_types_helper.rb
module WorkTypesHelper
end

rails/app/views/admin/cities/_form.html.erb
<%= form_for [:admin, @city] do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country_id, 'Country' %><br>
    <%= f.select :country_id,
      Country.all.map { |c| [c.name, c.id] },
                   { include_blank: true },
                   { class: 'chosen-select' }
    %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/app/views/admin/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_city_path(@city) %> |
<%= link_to 'Back', admin_cities_path %>

rails/app/views/admin/cities/index.html.erb
<h1>Listing Cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.country.name if city.country %></td>
        <td><%= link_to 'Show', admin_city_path(city) %></td>
        <td><%= link_to 'Edit', edit_admin_city_path(city) %></td>
        <td><%= link_to 'Destroy', admin_city_path(city), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_admin_city_path %>

rails/app/views/admin/cities/new.html.erb
<h1>New City</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_cities_path %>

rails/app/views/admin/cities/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @city.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @city.country.name if @city.country %>
</p>

<%= link_to 'Edit', edit_admin_city_path(@city) %> |
<%= link_to 'Back', admin_cities_path %>